repos:
# Linting
- repo: https://github.com/pycqa/flake8
  rev: 3.9.2 # can also add a git hash or tag
  hooks:
  - id: flake8
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
